use_frameworks!

pod 'Lores', :path => '../'
pod 'WolfCore', :path => '../../WolfCore/'

platform :ios, '11.0'

target 'Lores_Example' do

  target 'Lores_Tests' do
    inherit! :search_paths
  end
end
