use_frameworks!

target 'Lores_Example_iOS' do
  platform :ios, '11.3'
  pod 'Lores', :path => '../'
  pod 'WolfCore', :path => '../../WolfCore/'
end

target 'Lores_Example_macOS' do
    platform :macos, '10.13'
    pod 'Lores', :path => '../'
    pod 'WolfCore', :path => '../../WolfCore/'
end
